package canon_test

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"
	"time"

	"audittrail.dev/packages/ingestion-go/internal/canon"
	"audittrail.dev/packages/ingestion-go/internal/keys"
	"audittrail.dev/packages/ingestion-go/internal/merkle"
)

var update = flag.Bool("update", false, "rewrite schemas/test-vectors.json")

func sp(s string) *string { return &s }

type vecEvent struct {
	Input            map[string]any `json:"input"`
	PreviousHash     string         `json:"previous_hash"`
	CanonicalPayload string         `json:"canonical_payload"`
	Hash             string         `json:"hash"`
	Signature        string         `json:"signature"`
}

type vectors struct {
	Description   string              `json:"description"`
	SigningSeed   string              `json:"signing_seed_b64"`
	PublicKey     string              `json:"public_key_b64"`
	KeyID         string              `json:"key_id"`
	Events        []vecEvent          `json:"events"`
	MerkleRoot    string              `json:"merkle_root"`
	InclusionIdx  int                 `json:"inclusion_index"`
	InclusionPath []string            `json:"inclusion_path"`
	Checkpoint    map[string]any      `json:"checkpoint"`
	JCS           []map[string]string `json:"jcs"`
}

func build(t *testing.T) vectors {
	seed := make([]byte, 32)
	for i := range seed {
		seed[i] = byte(i)
	}
	priv := ed25519.NewKeyFromSeed(seed)
	pub := priv.Public().(ed25519.PublicKey)
	tenant := "3f2b1c9e-8d7a-4e6f-9a1b-2c3d4e5f6a7b"
	ts := time.Date(2026, 8, 2, 9, 30, 0, 123456789, time.UTC)

	evs := []canon.Event{
		{ID: "a1b2c3d4-0000-4000-8000-000000000001", TenantID: tenant, Timestamp: ts, AgentID: "billing-service",
			Action: "invoice.update", TargetResource: "invoice/42", Outcome: "allowed",
			HumanPrincipalID: sp("user_123"), Metadata: json.RawMessage(`{"amount":100.50,"currency":"EUR","z":1,"a":{"y":true,"b":null}}`)},
		{ID: "a1b2c3d4-0000-4000-8000-000000000002", TenantID: tenant, Timestamp: ts.Add(1500 * time.Millisecond),
			AgentID: "claude-code@2.1.0", ModelID: sp("claude-opus-5-5"), ModelVersion: sp("unknown"),
			DelegationChain: json.RawMessage(`[{"type":"human","id":"alice@example.com"},{"type":"agent","id":"claude-code@2.1.0"},{"type":"tool_call","id":"7","parent":null}]`),
			Action: "mcp.tools/call", TargetResource: "mcp://filesystem/tools/write_file", Outcome: "denied",
			Metadata: json.RawMessage(`{"args":{"path":"/etc/passwd","text":"é ☃ 😀 \"quoted\" \n tab\t"},"n":[1e21,1e-7,0.1,-0,123456789012345680000,5e-324]}`)},
		{ID: "a1b2c3d4-0000-4000-8000-000000000003", TenantID: tenant, Timestamp: ts.Add(3 * time.Second),
			AgentID: "unknown", Action: "mcp.resources/read", TargetResource: "mcp://docs/resources/file:///a%20b", Outcome: "error"},
	}
	v := vectors{
		Description: "Generated by `go test ./internal/canon -update`. Every AuditTrail implementation must reproduce these bytes exactly. Input timestamps have sub-ms precision on purpose: they must be truncated (not rounded) to ms.",
		SigningSeed: base64.StdEncoding.EncodeToString(seed), PublicKey: base64.StdEncoding.EncodeToString(pub), KeyID: keys.KeyID(pub),
	}
	prev := canon.Genesis
	var hs []string
	for _, e := range evs {
		h, payload, err := canon.HashEvent(prev, e)
		if err != nil {
			t.Fatal(err)
		}
		in := map[string]any{"id": e.ID, "tenant_id": e.TenantID, "timestamp": e.Timestamp.Format(time.RFC3339Nano),
			"human_principal_id": e.HumanPrincipalID, "agent_id": e.AgentID, "model_id": e.ModelID, "model_version": e.ModelVersion,
			"delegation_chain": json.RawMessage(nullIfEmpty(e.DelegationChain)), "action": e.Action, "target_resource": e.TargetResource,
			"outcome": e.Outcome, "metadata": json.RawMessage(nullIfEmpty(e.Metadata))}
		v.Events = append(v.Events, vecEvent{Input: in, PreviousHash: prev, CanonicalPayload: string(payload), Hash: h,
			Signature: keys.Sign(priv, canon.EventSigningMessage(h))})
		hs = append(hs, h)
		prev = h
	}
	root, _ := merkle.RootHex(hs)
	v.MerkleRoot = root
	v.InclusionIdx = 2
	v.InclusionPath, _ = merkle.InclusionProof(hs, 2)
	st := canon.CheckpointStatement{Type: canon.CheckpointType, TenantID: tenant, FirstSeq: 1, LastSeq: 3, RowCount: 3,
		MerkleRoot: root, HeadHash: prev, PrevCheckpointHead: canon.Genesis, CreatedAt: "2026-08-02T09:35:00.000Z"}
	sb, _ := st.Bytes()
	v.Checkpoint = map[string]any{"statement": string(sb), "signature": keys.Sign(priv, sb)}
	for _, in := range []string{`{"b":2,"a":1}`, `[1.0,-0,1e21,1e-7,0.000001,"é "]`, `{"€":1,"\r":2,"1":3,"a":{"c":[],"b":{}}}`} {
		out, err := canon.Canonicalize([]byte(in))
		if err != nil {
			t.Fatal(err)
		}
		v.JCS = append(v.JCS, map[string]string{"input": in, "output": string(out)})
	}
	return v
}

func nullIfEmpty(r json.RawMessage) []byte {
	if len(r) == 0 {
		return []byte("null")
	}
	return r
}

func TestVectors(t *testing.T) {
	v := build(t)
	got, _ := json.MarshalIndent(v, "", "  ")
	path := filepath.Join("..", "..", "..", "..", "schemas", "test-vectors.json")
	if *update {
		if err := os.WriteFile(path, append(got, '\n'), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%v (run with -update)", err)
	}
	var a, b any
	json.Unmarshal(got, &a)
	json.Unmarshal(want, &b)
	ga, _ := json.Marshal(a)
	gb, _ := json.Marshal(b)
	if string(ga) != string(gb) {
		t.Fatal("canonicalization drifted from schemas/test-vectors.json")
	}
}

func TestTamperChangesHash(t *testing.T) {
	e := canon.Event{ID: "x", TenantID: "t", Timestamp: time.Unix(0, 0), AgentID: "a", Action: "b", TargetResource: "c", Outcome: "allowed"}
	h1, _, _ := canon.HashEvent(canon.Genesis, e)
	e.Outcome = "denied"
	h2, _, _ := canon.HashEvent(canon.Genesis, e)
	if h1 == h2 {
		t.Fatal("outcome not covered by hash")
	}
}
